# Generated by Django 5.2.1 on 2025-06-18 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='MpesaReceiptNumber returned after successful payment.', max_length=100, null=True, verbose_name='M-Pesa Receipt Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Set to True when payment is received and session is locked in.', verbose_name='Is Confirmed?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, help_text='Extra details shared during booking.', null=True, verbose_name='Optional Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(verbose_name='Booking Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who booked the session (can be blank if user account is deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount Paid (KES)'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='booking',
            field=models.OneToOneField(help_text='The booking this payment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='Related Booking'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(help_text='Returned by Safaricom during STK push initiation.', max_length=100, unique=True, verbose_name='Checkout Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='Returned by Safaricom (usually same as Checkout ID).', max_length=100, null=True, verbose_name='Merchant Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(help_text='Phone number used for the payment.', max_length=15, verbose_name='M-Pesa Phone Number'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created in the system.', verbose_name='Received At'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_code',
            field=models.IntegerField(blank=True, help_text='Status code returned by Safaricom (0 means success).', null=True, verbose_name='Result Code'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_desc',
            field=models.CharField(blank=True, help_text="Safaricom's message about the transaction result.", max_length=255, null=True, verbose_name='Result Description'),
        ),
    ]
