# Generated by Django 5.2.1 on 2025-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_mpesapayment_transaction_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Marks the booking as paid once M-Pesa confirms it.', verbose_name='Payment Received?'),
        ),
    ]
