# Generated by Django 5.2.1 on 2025-06-20 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_confirmed_booking_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payment Received?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='Related Booking'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Checkout Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='M-Pesa Phone Number'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received At'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Result Code'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Result Description'),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='M-Pesa Receipt Number'),
        ),
    ]
