# Generated by Django 5.2.1 on 2025-06-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_global',
        ),
    ]
