# Generated by Django 5.2.1 on 2025-06-20 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to show this announcement to every user.', related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Target users'),
        ),
    ]
